language: perl
perl:
  - "5.28.2"
  - "5.30"
  - "blead"
matrix:
  include:
    - perl: 5.28.2
      env: COVERAGE=1
    - perl: 5.30
      env: COVERAGE=1
  allow_failures:
    - perl: "blead"
sudo: false             # faster builds as long as you don't need sudo access
cache:
  directories:
    - $HOME/perl5
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
script:
  - prove -lv t/   # parallel testing
after_success:
  - coverage-report
